# -*- coding: utf-8 -*-
"""RAG FLOW

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qUdq0LSfPE67m_eqW4PtHxjj59o9DtK4
"""

!pip install -q pypdf

from google.colab import files

uploaded = files.upload()

import pypdf

pdf_file = list(uploaded.keys())[0]

reader = pypdf.PdfReader(pdf_file)

text = ""

for page in reader.pages:
    text += page.extract_text() + "\n"

print("PDF Loaded Successfully")
print(text[:1000])

with open("document.txt", "w", encoding="utf-8") as f:
    f.write(text)

print("document.txt created")

app_code = '''
import streamlit as st
import os

from langchain_community.document_loaders import TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter

from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.chains import RetrievalQA

st.set_page_config(page_title="RAG Chatbot")

st.title("PDF RAG Chatbot")

api_key = st.text_input(
    "Enter Gemini API Key",
    type="password"
)

if api_key:

    os.environ["GOOGLE_API_KEY"] = api_key

    loader = TextLoader("document.txt")

    docs = loader.load()

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=50
    )

    chunks = splitter.split_documents(docs)

    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )

    db = FAISS.from_documents(
        chunks,
        embeddings
    )

    retriever = db.as_retriever()

    llm = ChatGoogleGenerativeAI(
        model="gemini-1.5-flash",
        temperature=0
    )

    qa = RetrievalQA.from_chain_type(
        llm=llm,
        retriever=retriever
    )

    query = st.text_input("Ask Question")

    if query:
        answer = qa.run(query)
        st.write(answer)
'''

with open("app.py","w") as f:
    f.write(app_code)

print("app.py created")

requirements = """
streamlit
langchain
langchain-community
langchain-huggingface
langchain-google-genai
sentence-transformers
faiss-cpu
pypdf
google-generativeai
"""

with open("requirements.txt","w") as f:
    f.write(requirements)

print("requirements.txt created")

!ls

from google.colab import files

files.download("app.py")

from google.colab import files

files.download("requirements.txt")

from google.colab import files

files.download("document.txt")